### ISSUE TITLE
API call

### ISSUE THREAD

**Issue by keshavvinayak01** [mkuchnik/PlumberApp#1]
Hi, I was wondering how I would use the "Plumber" Recommended mode of setting parameters in place of AUTOTUNE or heuristic via simple API calls. 

Do i use this API by calling tf.data.Plumber the same way I would invoke AUTOTUNE?

The documentation is not sufficient for me to understand how I would use Plumber guided mode of execution in some arbitrary Tensorflow model I create with tf.data preprocessing.

Please let me know,
thanks.

**Comment by mkuchnik** [comment]
Hi, the API is not the same as AUTOTUNE, as it requires some Dataset-producing function to be annotated. You can either call it with an annotation like [this](https://github.com/mkuchnik/PlumberApp/blob/6123f5bce36eec7dc75b6b9298054b493d930bdc/end_to_end/TPU/resnet-research-JAX-Distributed-Shampoo-tpu-v4-256/mlperf_input_pipeline.py#L159) or you can use some of the other annotations [here](https://github.com/mkuchnik/PlumberApp/blob/6123f5bce36eec7dc75b6b9298054b493d930bdc/plumber_analysis/src/plumber_analysis/annotations.py#L86).
